//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookStoreManagetment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public string idItem { get; set; }
        public string linkItem { get; set; }
        public string imageItem { get; set; }
        public string nameItem { get; set; }
        public int importPriceItem { get; set; }
        public int sellPriceItem { get; set; }
        public string descriptionItem { get; set; }
        public string barcode { get; set; }
        public int quantity { get; set; }
        public string typeItem { get; set; }
        public string supplierItem { get; set; }
        public string unit { get; set; }
    }
}
