//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookStoreManagetment.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bookStoreManagementEntities : DbContext
    {
        public bookStoreManagementEntities()
            : base("name=bookStoreManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<bill> bills { get; set; }
        public virtual DbSet<bookInformation> bookInformations { get; set; }
        public virtual DbSet<checkItem> checkItems { get; set; }
        public virtual DbSet<custommer> custommers { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<importBill> importBills { get; set; }
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<itemSummary> itemSummaries { get; set; }
        public virtual DbSet<profitSummary> profitSummaries { get; set; }
        public virtual DbSet<sellBill> sellBills { get; set; }
        public virtual DbSet<studytoolsInformation> studytoolsInformations { get; set; }
        public virtual DbSet<supplier> suppliers { get; set; }
    }
}
