//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookStoreManagetment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public string idSupplier { get; set; }
        public string nameSupplier { get; set; }
        public string addressSupplier { get; set; }
        public string emailSupplier { get; set; }
        public string phoneNumberSupplier { get; set; }
        public string statusSupplier { get; set; }
        public string website { get; set; }
        public string fax { get; set; }
        public string masothue { get; set; }
    }
}
