//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookStoreManagetment
{
    using System;
    using System.Collections.Generic;
    
    public partial class profitSummary
    {
        public int idPayHistory { get; set; }
        public string billCode { get; set; }
        public string billType { get; set; }
        public int rootPrice { get; set; }
        public int payPrice { get; set; }
        public int exchangePrice { get; set; }
        public string codeCustomer { get; set; }
        public int idEmployee { get; set; }
        public System.DateTime sellDay { get; set; }
        public string nameCustomer { get; set; }
        public string nameEmployee { get; set; }
        public string typeGroup { get; set; }
        public string payment { get; set; }
        public string nameBill { get; set; }
        public string note { get; set; }
        public Nullable<int> budget { get; set; }
    
        public virtual bill bill { get; set; }
        public virtual employee employee { get; set; }
    }
}
