//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookStoreManagetment
{
    using System;
    using System.Collections.Generic;
    
    public partial class sellBill
    {
        public int idSell { get; set; }
        public string billCodeSell { get; set; }
        public int idEmployee { get; set; }
        public int number { get; set; }
        public System.DateTime sellDate { get; set; }
        public int idCustomer { get; set; }
        public string idItem { get; set; }
        public int unitPrice { get; set; }
        public int discount { get; set; }
        public string note { get; set; }
        public string billStatus { get; set; }
        public System.DateTime deliveryDate { get; set; }
        public System.DateTime licenseDate { get; set; }
        public string tag { get; set; }
        public string deliveryMethod { get; set; }
        public string paymentMethod { get; set; }
    
        public virtual bill bill { get; set; }
        public virtual item item { get; set; }
    }
}
