//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookStoreManagetment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public int idAccount { get; set; }
        public string nameAccount { get; set; }
        public string passwordAccount { get; set; }
        public string typeAccount { get; set; }
    }
}
