//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookStoreManagetment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookInformation
    {
        public int sttInformation { get; set; }
        public string idBook { get; set; }
        public string typeContent { get; set; }
        public string typeMaterial { get; set; }
        public string size { get; set; }
        public Nullable<int> numberOfPages { get; set; }
        public string author { get; set; }
        public string translator { get; set; }
        public string NXB { get; set; }
        public string NPH { get; set; }
    }
}
