//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookStoreManagetment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int sttEmployee { get; set; }
        public string idEmployee { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string phoneNumber { get; set; }
        public string employeeType { get; set; }
        public string employeeAddress { get; set; }
        public string employeeEmail { get; set; }
        public string sex { get; set; }
        public string citizenIdentification { get; set; }
        public System.DateTime dateOfBirth { get; set; }
        public string nameAccount { get; set; }
        public Nullable<int> employeeSalary { get; set; }
        public string employeeNote { get; set; }
        public string employeeImagePath { get; set; }
    }
}
