//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookStoreManagetment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class itemSummary
    {
        public int idSummary { get; set; }
        public string billCode { get; set; }
        public string billType { get; set; }
        public string idItem { get; set; }
        public int quantityBefore { get; set; }
        public int incurred { get; set; }
        public int quantityAfter { get; set; }
        public System.DateTime incurredDay { get; set; }
        public Nullable<int> idCustomer { get; set; }
        public int idEmployee { get; set; }
    }
}
