//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookStoreManagetment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class khachtrahang
    {
        public int idTrahang { get; set; }
        public string billCodeTra { get; set; }
        public string billCodeSell { get; set; }
        public string nameEmployee { get; set; }
        public int number { get; set; }
        public System.DateTime sellDate { get; set; }
        public string idCustomer { get; set; }
        public string idItem { get; set; }
        public int unitPrice { get; set; }
        public int discount { get; set; }
        public string lido { get; set; }
        public string trangthai { get; set; }
        public string nameCustomer { get; set; }
        public string unit { get; set; }
    }
}
