//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookStoreManagetment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mail
    {
        public int idMail { get; set; }
        public string typeMail { get; set; }
        public System.DateTime updateDate { get; set; }
        public string subjectMail { get; set; }
        public string content { get; set; }
        public string descriptionMailType { get; set; }
        public string statusMail { get; set; }
        public string sender { get; set; }
        public Nullable<System.DateTime> autosentDate { get; set; }
        public string typesent { get; set; }
    }
}
