//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookStoreManagetment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class profitSummary
    {
        public int idPayHistory { get; set; }
        public string billCode { get; set; }
        public string billType { get; set; }
        public int rootPrice { get; set; }
        public int paidAmount { get; set; }
        public int profit { get; set; }
        public Nullable<int> idCustomer { get; set; }
        public int idEmployee { get; set; }
        public System.DateTime sellDay { get; set; }
    
        public virtual bill bill { get; set; }
        public virtual custommer custommer { get; set; }
        public virtual employee employee { get; set; }
    }
}
