//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookStoreManagetment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sentmail
    {
        public int idSent { get; set; }
        public int idMail { get; set; }
        public string receiverMail { get; set; }
        public string mailStatus { get; set; }
        public System.DateTime dateSent { get; set; }
        public string sender { get; set; }
        public string subjectMail { get; set; }
        public string typeMail { get; set; }
    }
}
