//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookStoreManagetment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class studytoolsInformation
    {
        public int sttInformation { get; set; }
        public string idStudyTool { get; set; }
        public string origin { get; set; }
        public string distributor { get; set; }
        public string typecontent { get; set; }
    }
}
